In [1]:
import pandas as pd
from zipfile import ZipFile
import yfinance as fp
import datetime

In [2]:
# with ZipFile("Data/NIFTY50_all.csv.zip","r") as ref:
#     unzip = ref.extractall("Data/Bnk_NIFTY50")
# ref.close()

In [3]:
today = datetime.date.today()
year  = today-datetime.timedelta(days=7300) #20 Years
Stocks = ['AAPL', 'MSFT', 'IBM', 'GE', 'JNJ']
data = fp.download(Stocks,start=year,end=today,group_by="ticker")
data

C:\Users\lipun\AppData\Local\Temp\ipykernel_27428\1640078772.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = fp.download(Stocks,start=year,end=today,group_by="ticker")
[*********************100%***********************]  5 of 5 completed

Ticker            AAPL                                                 \
Price             Open        High         Low       Close     Volume
Date
2005-07-25    1.322084    1.330800    1.314270    1.316674  294627200
2005-07-26    1.322685    1.325690    1.303149    1.311264  268592800
2005-07-27    1.317275    1.324488    1.282412    1.322083  283749200
2005-07-28    1.317876    1.322385    1.301347    1.316374  251311200
2005-07-29    1.309160    1.333805    1.270090    1.281811  562080400
...                ...         ...         ...         ...        ...
2025-07-14  209.929993  210.910004  207.539993  208.619995   38840100
2025-07-15  209.220001  211.889999  208.919998  209.110001   42296300
2025-07-16  210.300003  212.399994  208.639999  210.160004   47490500
2025-07-17  210.570007  211.800003  209.589996  210.020004   48068100
2025-07-18  210.869995  211.789993  209.699997  211.179993   48939500

Ticker             JNJ                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2005-07-25   36.089126   36.111594   35.555512   35.577980   6741900  ...
2005-07-26   35.297142   35.594842   35.201653   35.201653  12640400  ...
2005-07-27   35.443186   36.381222   35.398251   36.252033  10789500  ...
2005-07-28   36.218336   36.420544   36.016124   36.358761   6391600  ...
2005-07-29   36.330678   36.386847   35.915020   35.926254   6143200  ...
...                ...         ...         ...         ...       ...  ...
2025-07-14  156.869995  157.470001  155.520004  156.820007  10185600  ...
2025-07-15  156.360001  157.190002  154.800003  155.169998   6873200  ...
2025-07-16  160.300003  166.119995  159.800003  164.779999  22134800  ...
2025-07-17  163.179993  164.699997  162.300003  162.979996  11295700  ...
2025-07-18  163.929993  165.100006  163.360001  163.699997   9792600  ...

Ticker              GE                                                \
Price             Open        High         Low       Close    Volume
Date
2005-07-25  102.716846  102.716846  101.257796  101.462059   3783503
2005-07-26  101.637111  102.454180  101.228576  101.257759   3420410
2005-07-27  101.286978  101.607963  101.111889  101.549606   3482466
2005-07-28  101.782990  102.279064  101.549544  101.782990   3392115
2005-07-29  101.549567  101.899735  100.644958  100.674141   4118009
...                ...         ...         ...         ...       ...
2025-07-14  256.190002  262.459991  256.000000  262.339996   7502200
2025-07-15  263.920013  265.059998  261.739990  264.670013   9392400
2025-07-16  264.000000  266.859985  262.029999  266.179993  11912900
2025-07-17  269.799988  272.799988  258.160004  260.279999  16260200
2025-07-18  265.399994  269.700012  262.559998  263.269989   8612100

Ticker             IBM
Price             Open        High         Low       Close   Volume
Date
2005-07-25   43.650876   43.931559   43.619692   43.765228  4662859
2005-07-26   43.739229   43.843182   43.583294   43.723633  4751873
2005-07-27   43.557318   43.728842   43.042738   43.593700  5085861
2005-07-28   43.427368   43.645673   43.281831   43.557312  6474426
2005-07-29   43.297406   43.635261   43.255823   43.380569  4529494
...                ...         ...         ...         ...      ...
2025-07-14  282.829987  284.929993  281.709991  283.790009  2857100
2025-07-15  283.769989  284.149994  280.730011  282.700012  2864100
2025-07-16  282.750000  283.869995  279.869995  281.920013  2804800
2025-07-17  281.500000  283.459991  280.899994  282.000000  3337200
2025-07-18  283.380005  287.160004  282.220001  285.869995  4477600

[5028 rows x 25 columns]

In [4]:
new = []
for i in Stocks:
    df = data[i].copy()
    df = df.reset_index()
    df["Stocks"] = i
    new.append(df)
new_data = pd.concat(new)
new_data

Price,Date,Open,High,Low,Close,Volume,Stocks
0,2005-07-25,1.322084,1.330800,1.314270,1.316674,294627200,AAPL
1,2005-07-26,1.322685,1.325690,1.303149,1.311264,268592800,AAPL
2,2005-07-27,1.317275,1.324488,1.282412,1.322083,283749200,AAPL
3,2005-07-28,1.317876,1.322385,1.301347,1.316374,251311200,AAPL
4,2005-07-29,1.309160,1.333805,1.270090,1.281811,562080400,AAPL
...,...,...,...,...,...,...,...
5023,2025-07-14,156.869995,157.470001,155.520004,156.820007,10185600,JNJ
5024,2025-07-15,156.360001,157.190002,154.800003,155.169998,6873200,JNJ
5025,2025-07-16,160.300003,166.119995,159.800003,164.779999,22134800,JNJ
5026,2025-07-17,163.179993,164.699997,162.300003,162.979996,11295700,JNJ
5027,2025-07-18,163.929993,165.100006,163.360001,163.699997,9792600,JNJ

In [5]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25140 entries, 0 to 5027
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    25140 non-null  datetime64[ns]
 1   Open    25140 non-null  float64
 2   High    25140 non-null  float64
 3   Low     25140 non-null  float64
 4   Close   25140 non-null  float64
 5   Volume  25140 non-null  int64
 6   Stocks  25140 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 1.5+ MB

In [6]:
#Saving File
new_data.to_csv("Data/DataPreparation.csv",index=False)

<h1><b>FINAL REPORT: DATA-PREPARATION</b></h1>
    <li>
        Data-Source: <a href="yfinance">Yfinance</a>
    </li>
    <li>Converted Raw Dataset to Structured Format With a New Feature as Stocks</li>
    <li><b>Total Samples:</b> 25135</li>
    <li><b>Total Independent Features: </b>"Date","Open","High","Low" ,"Volume and "Stocks"</li>
    <li><b>Dependent Feature:</b> "Close"</li>
    <center><b><li>Stocks Names</li></b></center>
    <table>
        <th>Stocks</th>
        <th>Symbols</th>
        <tr><td>AAPL</td><td>Apple</td></tr>
        <tr><td>MSFT</td><td>Microsoft</td></tr>
        <tr><td>IBM</td><td>IBM</td></tr>
        <tr><td>GE</td><td>General Electric</td></tr>
       <tr><td>JNJ</td><td>Johnson & Johnson</td></tr>
    </table>
    <center><li><b>Feature Dtypes</b></li></center>
    <table>
        <th>Features</th>
        <th>DataTypes</th>
        <tr><td>Date</td><td>datetime64</td></tr>
        <tr><td>Open</td><td>float64</td></tr>
        <tr><td>High</td><td>float64</td></tr>
        <tr><td>Low</td><td>float64</td></tr>
        <tr><td>Close</td><td>float64</td></tr>
        <tr><td>Volume</td><td>int64</td></tr>
        <tr><td>Stocks</td><td>object</td></tr>
    </table>